[profile.default]
solc = "0.8.17"
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
fuzz_runs = 10000
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[etherscan]
opBnbTestnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-opbnb-testnet.bscscan.com/api", chain = 5611 }
onusTestnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-testnet.onuschain.io/api", chain = 1945 }